# Generated by Django 3.2.4 on 2021-06-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[[0, 'male'], [1, 'female']])),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=5)),
                ('type', models.IntegerField(choices=[[0, 'poleras'], [1, 'pantalones'], [2, 'camisas'], [3, 'polerones'], [4, 'vestidos'], [5, 'zapatillas']])),
                ('brand', models.IntegerField(choices=[[0, 'nike'], [1, 'adidas'], [2, 'rebook'], [3, 'levis'], [4, 'lacoste'], [5, 'supreme'], [6, 'gucci']])),
                ('price', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('snom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('msn', models.CharField(max_length=300)),
            ],
        ),
    ]
