# Generated by Django 3.2.4 on 2021-06-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210624_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='snom',
            new_name='username',
        ),
    ]
